### ISSUE TITLE
Declare local variables after exports.

### ISSUE THREAD

**Issue by coballast** [coballast/threejs-browserify-conversion-utility#18]
Since function hoisting has been added, code like this has been generated:

```javascript
module.exports.AddEquation = AddEquation;
module.exports.AddOperation = AddOperation;
module.exports.AdditiveBlending = AdditiveBlending;
module.exports.AlphaFormat = AlphaFormat;
module.exports.AlwaysDepth = AlwaysDepth;
module.exports.BackSide = BackSide;
module.exports.BasicShadowMap = BasicShadowMap;
module.exports.ByteType = ByteType;
...
var AddEquation = ...
...
```

Easy enough to manually correct, since I think it only happens in a few places, but it would be nice if it figured this out automagically.

**Comment by kumavis** [comment]
Should only hoist functions, not vars

**Comment by coballast** [comment]
Am confused. Code example?

**Comment by coballast** [comment]
Read it wrong, nevermind.

**Comment by HMUDesign** [comment]
Of the files where I encountered this problem (I was only building a very simple scene), some of them were constructors defined using ```var Foo = function() {};``` rather than ```function Foo() {}```. Those could be switched over to the function method. For ones where it must be an object (perhaps in others), why not export on the same line as the definition? ```var Foo = module.exports.Foo = {};``` Also as a note, that is how es6 exports are generally defined: ```export function Foo() {}```

**Comment by kumavis** [comment]
@HMUDesign theres some subtle ordering requirements to get exports to work correctly during cyclic deps. [see here](https://github.com/coballast/threejs-browserify-conversion-utility/issues/9#issuecomment-87449916)

**Comment by coballast** [comment]
I fixed this by adding an extra pass.
