### ISSUE TITLE
Compiling shader chunks into final build.

### ISSUE THREAD

**Issue by coballast** [coballast/threejs-browserify-conversion-utility#27]
The three.js build system compiles shader chunks into the distribution at build time.
The details are in https://github.com/mrdoob/three.js/blob/master/utils/build/build.py

We need a way to do this with browserify.

**Comment by benaadams** [comment]
I use the js build with node rather than the python version: https://github.com/mrdoob/three.js/blob/master/utils/build/build.js

**Comment by coballast** [comment]
@benaadams You are a god among men. Thank you for pointing this out.

**Comment by HMUDesign** [comment]
A few of the commenters on https://github.com/mrdoob/three.js/issues/4776 suggested the use of glslify. I only looked at it briefly, but my understanding of it is that the command line tool can be used to compile multiple snippets into a complete shader. To do this with the threejs shaders i think would add lots of bloat, as there is much glsl code shared between them. (otherwise MrDoob would have injected the complete shaders). The browser version of glslify can be used as an extension to browserify, though I do not think adding a dependency to threejs is the right direction. Additionally, it would only work with browserify, which is contrary to my interest in the project. =]

The direction I am looking right now is to leave the shader usage as is, and simply use require to pull in the shader info. My hope is that browserify can be easily extended in a manner that can also be applied to SystemJS and other loaders, resulting in just outputting the text content.

Ideally, ShaderLib would become dependent upon the fragments themselves, rather than through ShaderChunk, and would be furthermore separated into the individual shaders to different files for dependency purposes.

Thoughts?

**Comment by kumavis** [comment]
stackgl and glslify are awesome projects. That said, I advocate for a smaller scope of this three.js conversion project, so lets not change the behaviour here. That can come later! To help make our case in merging this new architecture, we should create a list of neato future todo's, like glsl modules.

**Comment by benaadams** [comment]
My main interesting in glslify was for glslify-optimize; but alas it uses a native rather than js library to do the optimisation so wouldn't work in a browser :( ( https://github.com/aras-p/glsl-optimizer )

**Comment by kumavis** [comment]
maybe a good target for an [emscripten](https://github.com/kripken/emscripten) build

**Comment by coballast** [comment]
I'm with @kumavis on this one. Our (or my) primary focus is to get a working THREE.js bundle built using browserify while modifying the way the system is structured as little as possible. The intent is to try and get this merged into the mainline as the new build system. Integrating glslify is on my radar (as well as moving things over to es6), but getting a browserify build working is my first priority.

**Comment by HMUDesign** [comment]
I have it functioning now with both Systemjs and Browserify. In both cases, the shader chunks are required just like a javascript file. Then there is a small script which, when it sees a request for a .glsl file, returns the text. For Browserify, this is called a transform.

The necessary files can be found at https://gist.github.com/HMUDesign/9ca7ff210d4eb4e87e9c Additionally, the following will be needed to be added to the threejs package.json file. The path to glsl_chunk will need to be modified to point to the location of the file.

```
  "browserify": {
    "transform": [ "./glsl_chunk" ]
  },
```

It would be useful if it were possible to include system_glsl.js in the repo, for use with systemjs.

For those of you curious about using it in JSPM, I cloned the repo to my project directory into threejs-modules. The system_glsl.js needs to be included in your html before config.js, and the following needs to be added your config.js under paths:

```
    "threejs/*": "threejs-modules/src/*.js",
    "threejs/*.glsl": "threejs-modules/src/*.glsl",
```

**Comment by coballast** [comment]
@HMUDesign That is so cool! Thank you so much!

**Comment by coballast** [comment]
@HMUDesign Okay. I integrated your changes into the browserify branch. Everyone please take a look at the latest changes and critique them, but it looks good to me. Closing this.

**Comment by coballast** [comment]
I will keep your systemjs source file around, but I'm not going to add it to the repo for the time being. Once/if this build system gets merged with the mainline, we can make that a pr as an additional feature.

**Comment by coballast** [comment]
The bonus features list is here: coballast/three.js#2
